schema_version: 1

context:
  version: "0.1.49"

package:
  name: rsloop
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/r/rsloop/rsloop-${{ version }}.tar.gz
    sha256: 413af1c777dd66018067db7de51ad8c1cacc9956c1d8034d570a61bab077509f

build:
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin
  host:
    - maturin
    - pip
    - python
  run:
    - python

tests:
  - python:
      imports: rsloop
      pip_check: true

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://rustedbytes.github.io/rsloop
  repository: https://github.com/RustedBytes/rsloop
  summary: An event loop for asyncio written in Rust.

extra:
  recipe-maintainers:
    - davidbrochart
